title: Digital Notes Garden
name: Boris Mann
user_description: "Open Source. Community. Decentralized Web. Building dev tools at Fission. Cooks & eats."
description: "Second Brain, Daily Notes, and long term archive of Boris Mann"
notes_url: "https://bmannconsulting.com"
notes_title: Notes, Articles, and Links
notes_tagline: Information gardening
profile_pic: /assets/bmann_hair_orange_256x256.png
favicon: /assets/bmann_hair_orange_256x256.png
copyright_name: Boris Mann
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bmannconsulting.com" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

exclude: ['.env', 'fission.yaml', 'gemset.nix', 'pages', 'fission.yaml', 'blog.code-workspace', 'netlify.toml', '_ignore']

markdown: CommonMarkGhPages
# markdown: kramdown

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

# kramdown:
#  input: GFM
#  hard_wrap: false
#  math_engine: mathjax
#  smart_quotes: ["apos", "apos", "quot", "quot"]
#  syntax_highlighter: rouge

# Build settings
theme: null
plugins:
#  - jekyll-feed 
#  - jekyll-sitemap 
  - jekyll-last-modified-at
  - jekyll-commonmark-ghpages

sass:
  style: compressed

# Default permalink
permalink: /:path/:title/

collections:
    notes:
      output: true
      permalink: /:title/

#disqus:
#  shortname: raghuveerdotnet

defaults:
  - scope:
      path: "_posts/*"
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
      content-type: post
      section: blog
  - scope:
      path: "_posts/archive/*"
      type: posts
    values:
      layout: post
      permalink: /archive/:year/:month/:day/:title/
      content-type: post
      section: archive
  - scope:
      path: "_posts/journal/*"
      type: posts
    values:
      layout: post
      permalink: /journal/:year/:month/:day/
      content-type: post
      section: journal
  - scope:
      path: "_notes/*"
      type: notes
    values:
      layout: post
      content-type: notes
