title: Digital Notes Garden
name: Boris Mann
user_description: "Open Source. Community. Decentralized Web. Building dev tools at Fission. Cooks & eats."
description: "Second Brain, Daily Notes, and long term archive of Boris Mann"
notes_url: "https://bmannconsulting.com"
notes_title: Notes, Articles, and Links
notes_tagline: Information gardening
profile_pic: /assets/bmann_hair_orange_256x256.png
favicon: /assets/bmann_hair_orange_256x256.png
copyright_name: Boris Mann
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bmannconsulting.com" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8
timezone: America/Vancouver

# digital garden

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

exclude: ['_includes/notes_graph.json', '.env', 'gemset.nix', 'pages', 'fission.yaml', 'blog.code-workspace', 'netlify.toml', '_ignored', '_archive', '.vscode', '.obsidian', "tiddlywiki"]

include: ['.well-known', '_pages']

# markdown: CommonMarkGhPages
markdown: kramdown

# commonmark:
#  options: ["SMART", "FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "table"]

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

# Build settings
theme: null

plugins:
  - jekyll-last-modified-at
  # - jekyll-commonmark-ghpages

sass:
  sass_dir:          _sass
  style:            :compressed

# Default permalink
permalink: /:title/

collections:
  notes:
    output: true
    permalink: /notes/:slug/

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "_posts/blog/*"
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
      section: blog
  - scope:
      path: "_posts/archive/*"
      type: posts
    values:
      layout: post
      permalink: /archive/:year/:month/:day/:title/
      section: archive
  - scope:
      path: "_notes/*"
    values:
      layout: "note"
      section: note

