title: "Boris Mann's Homepage"
name: "Boris Mann's Homepage"
user_description: "Open Source. Community. DWeb. Building edge computing at Fission with IPFS. Cooks & eats."
description: "Daily journals with links and asides, digital garden notes, and occasional long form blogs"
notes_url: "https://notes.bmannconsulting.com"
tags_url: "https://notes.bmannconsulting.com/#/page"
profile_pic: /assets/bmann_hair_orange_256x256.png
favicon: /assets/bmann_hair_orange_256x256.png
copyright_name: Boris Mann
author: Boris Mann
url: "https://bmannconsulting.com"
baseurl: ''
encoding: utf-8
timezone: America/Vancouver

# digital garden

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

exclude: ['_includes/notes_graph.json', '.env', 'gemset.nix', 'fission.yaml', 'blog.code-workspace', 'netlify.toml', '_ignored', '_archive', '.vscode', '.obsidian', '.gitignore', '.github', 'README.md', "_template", ".obsidian"]

include: ['.well-known', '_pages', '_redirects']

# markdown: CommonMarkGhPages
markdown: kramdown

# commonmark:
#  options: ["SMART", "FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "table"]

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

# Build settings
theme: null

plugins:
  - jekyll-last-modified-at
# - jekyll-commonmark-ghpages

sass:
  sass_dir:          _sass
  style:            :compressed

# Default permalink
permalink: /:title/

collections:
  notes:
    output: true
    permalink: "/notes/:slug/"
  journals:
    output: true
    permalink: "/journal/:slug/"

defaults:
  - scope:
      path: "_posts/*"
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
      section: blog
  - scope:
      path: "_notes/*"
    values:
      layout: "note"
      section: note
  - scope:
      path: "_journals/*"
    values:
      layout: "journal"
      section: journal

